apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    owner: minesoft-corp
spec:
  replicas: 1
  selector: 
    matchLabels:
      app: minecraft-app
  template:
    metadata:
      labels:
        app: minecraft-app
    spec:
      volumes:
        - name: minecraft-file
          persistentVolumeClaim:
            claimName: minefile
      containers:
        - name: minecraft-app
          image: openhack/minecraft-server:2.0
          volumeMounts:
          - name: minecraft-file
            mountPath: /data
          - name: minecraft-file
            mountPath: /mods
          - name: minecraft-file
            mountPath: /config
          - name: minecraft-file
            mountPath: /plugins
          - name: minecraft-file
            mountPath: /home/minecraft
          ports:
          - containerPort: 25565
            name: game-port
          - containerPort: 25575
            name: rcon-port
          env:
          - name: EULA
            value: "TRUE"